// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1hj2GZETR4E0di2uR9ldWIyJRszazYrM',
    appId: '1:434205063936:web:6bb0820cff63e6979e51e5',
    messagingSenderId: '434205063936',
    projectId: 'firebase-erdenay',
    authDomain: 'fir-erdenay.firebaseapp.com',
    storageBucket: 'firebase-erdenay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl-CIbitvTRTZNzY3TczJ2tyl2125DYEw',
    appId: '1:434205063936:android:f9e702ba2cb7ca279e51e5',
    messagingSenderId: '434205063936',
    projectId: 'firebase-erdenay',
    storageBucket: 'firebase-erdenay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL5fKESYzX6afyY07TXisYBGcOrW-zOgM',
    appId: '1:434205063936:ios:3f588b4404bc8a2c9e51e5',
    messagingSenderId: '434205063936',
    projectId: 'firebase-erdenay',
    storageBucket: 'firebase-erdenay.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL5fKESYzX6afyY07TXisYBGcOrW-zOgM',
    appId: '1:434205063936:ios:3f588b4404bc8a2c9e51e5',
    messagingSenderId: '434205063936',
    projectId: 'firebase-erdenay',
    storageBucket: 'firebase-erdenay.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1hj2GZETR4E0di2uR9ldWIyJRszazYrM',
    appId: '1:434205063936:web:5bcf63a1851b04249e51e5',
    messagingSenderId: '434205063936',
    projectId: 'firebase-erdenay',
    authDomain: 'fir-erdenay.firebaseapp.com',
    storageBucket: 'firebase-erdenay.appspot.com',
  );
}
